id: IEF7674A2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T15:48:47+00:00'
last_modified: '2022-06-07T12:09:56.503100+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17345
  title: འཁོར་ལོ་སྡོམ་པའི་དབང་ཆོག་ངག་འདོན་གྱི་རིམ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4496':
      image_group_id: I8LS17353
      title: Volume 1 of 'khor lo sdom pa'i dbang chog ngag 'don gyi rim pa/
      total_pages: 314
      order: 1
      base_file: 4496.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
